export const GET_ALL_SHOP_REQUEST = "GET_ALL_SHOP_REQUEST";
export const GET_ALL_SHOP_SUCCESS = "GET_ALL_SHOP_SUCCESS";
export const GET_ALL_SHOP_FAIL = "GET_ALL_SHOP_FAIL";

export const POST_SHOP_REQUEST = "POST_SHOP_REQUEST";
export const POST_SHOP_SUCCESS = "POST_SHOP_SUCCESS";
export const POST_SHOP_FAIL = "POST_SHOP_FAIL";
export const POST_SHOP_RESET = "POST_SHOP_RESET";

export const PUT_SHOP_REQUEST = "PUT_SHOP_REQUEST";
export const PUT_SHOP_SUCCESS = "PUT_SHOP_SUCCESS";
export const PUT_SHOP_FAIL = "PUT_SHOP_FAIL";
export const PUT_SHOP_RESET = "PUT_SHOP_RESET";

export const GET_BY_ID_SHOP_REQUEST = "GET_BY_ID_SHOP_REQUEST";
export const GET_BY_ID_SHOP_SUCCESS = "GET_BY_ID_SHOP_SUCCESS";
export const GET_BY_ID_SHOP_FAIL = "GET_BY_ID_SHOP_FAIL";
export const GET_BY_ID_SHOP_RESET = "GET_BY_ID_SHOP_RESET";

export const DELETE_SHOP_REQUEST = "DELETE_SHOP_REQUEST";
export const DELETE_SHOP_SUCCESS = "DELETE_SHOP_SUCCESS";
export const DELETE_SHOP_FAIL = "DELETE_SHOP_FAIL";
export const DELETE_SHOP_RESET = "DELETE_SHOP_RESET";
